### ISSUE TITLE
UV coordinates within plane

### ISSUE THREAD

**Issue by ppizarror** [StoccoDavide/acme#10]
Hi! I need the ``(U, V)`` coordinates given a ``(X, Y, Z)`` coplanar to a plane ``p``, for example, for plane defined in:

```cpp
acme::point pA(5.02339, -0.81223, -1.13819); // Origin
acme::point pB(2.32428, 2.78375, 1.50523);
acme::point pC(-0.29562, -0.53994, 2.78661);
acme::triangle t(pA, pB, pC);
acme::plane p(pA, t.normal());
```

And taking as basis ``e1``, ``e2``:

```cpp
acme::vec3 n = p.normal();
acme::vec3 e1 = n.cross(acme::vec3(1, 0, 0)).normalized();
if (e1.isZero()) e1 = n.cross(acme::vec3(0, 0, 1)).normalized();
acme::vec3 e2 = n.cross(e1).normalized();
```

Computing UV for any coordinate is relatively easy, by computing the ``dot`` product of the base and the relative distance of any point to the origin of the plane. For example, for point ``point``:

```cpp
acme::point pointRelative = point - p.origin();
acme::vec2 pointUV(e1.dot(pointRelative), e2.dot(pointRelative));
```

The question is, can we add this feature to the plane object? It is desirable in acme? All previous steps can be resumed on a single function

```cpp
p.getUV(acme::point);
p.fromUV(acme::vec2);
```

Examples:

```cpp
acme::point xyz(1.10808, -2.2061, 1.45032);
acme::vec2 uv = p.getUV(xyz); // [ -8.902579e-01, 4.814598e+00 ]'
acme::point p =p.fromUV(uv); // p == xyz
```

- **Why this is important or needed?** Well... I need to triangulate coplanar points in 3D. Thus, using their UV representation is much simpler as algorithms like constrained Delaunay/Voronoi are simple to implement... also allows for reducing dimensionality and performing other planar algorithms.

Greetings!

**Comment by StoccoDavide** [comment]
Hi! `acme` has been initially thought only for strictly 3D geometrical operations but I can add the feature you requested.

If you need 2D support, you have good ideas on how to support mixed 2/3D operations, and you want to contribute to the repo, we can think about adding together the 2D section to `acme`.

Greetings!

**Comment by ppizarror** [comment]
I think you are right... maybe we can address that in the future, I'll close this for now. Thanks!
