### ISSUE TITLE
Rename acme.hh to acme.h

### ISSUE THREAD

**Issue by ppizarror** [StoccoDavide/acme#3]
Hi again. When compiling acme using Qt, the following warning is thrown if acme.hh is added to a target INTERFACE:

```cmake
Policy CMP0100 is not set: Let AUTOMOC and AUTOUIC process .hh files.  Run
  "cmake --help-policy CMP0100" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  For compatibility, CMake is excluding the header file(s):

    "P:/IE3/DEHA-E2-RVTGRAPH/lib/acme/include/acme/acme.hh"

  from processing by AUTOMOC and AUTOUIC.  If any of the files should be
  processed, set CMP0100 to NEW.  If any of the files should not be
  processed, explicitly exclude them by setting the source file property
  SKIP_AUTOGEN:

    set_property(SOURCE file.hh PROPERTY SKIP_AUTOGEN ON)
```

That issue can be easily solved if ``acme.hh`` is renamed to ``acme.h``. As far as I can see, there is no major difference.

Greetings,

**Comment by StoccoDavide** [comment]
Hi, I thought about this issue but I want to stick to the updated structure we are coherently using. I am sorry but I cannot fulfil your request.

Greetings,
Davide
