### ISSUE TITLE
Error in Ray.isInside(Point)

### ISSUE THREAD

**Issue by ppizarror** [StoccoDavide/acme#4]
Hi. I noticed a critical bug regarding ``Ray.isInside`` method. Actually, both ``Line.isInside`` and ``Ray.IsInside`` methods are equal, which has important issues. See the following case:

```cpp
point Origin(0, 0, 0);
vec3 Direction(0, 1, 0);
ray Ray(Origin, Direction);
```

In this example, the ray starts at the origin, propagating infinitely on the x-axis. However, the following test fails (I'm using GoogleTest #2):

```cpp
ASSERT_FALSE(Ray.isInside(point(0, -1, 0))); // FAILS
```

This happens because the cross product is zero, however, the projection of the given point ``(0, -1, 0)`` does not lie on the ray. To solve this, we must check the scalar (dot) is positive. This solves the issue. Now, the following tests pass:

```cpp
TEST(AcmeTEST, TestRayPointIntersection) {
    point Origin(0, 0, 0);
    vec3 Direction(0, 1, 0);
    ray Ray(Origin, Direction);

    ASSERT_FALSE(Ray.isInside(point(0, -1, 0))); // PASS
    ASSERT_FALSE(Ray.isInside(point(0, -100, 0))); // PASS
    ASSERT_FALSE(Ray.isInside(point(0.1, 1, 0))); // PASS
    ASSERT_TRUE(Ray.isInside(point(0, 0, 0))); // PASS
    ASSERT_TRUE(Ray.isInside(point(0, 10, 0))); // PASS
}
```

**Comment by StoccoDavide** [comment]
Dear Pablo,

Thank very much you for reporting the bug, I will address this issue in few hours.
You are the first person trying to use my library so be patient, there may be some bug as you noticed 😉.

I'm looking forward to hearing more of your suggestions!

Greetings,
Davide
