### ISSUE TITLE
Fix point intersection

### ISSUE THREAD

**Issue by ppizarror** [StoccoDavide/acme#7]
Hi! There is a problem regarding point intersection using pointers; see https://github.com/StoccoDavide/acme/blob/main/src/intersection.cc#L67-L73

We assume the point level is 1. Thus, the sum of two points should be ``100*1 + 1`` = ``101``. However, in the code, the value is compared against ``202``. The same issue is happing with every other combination of entities.

- Fixed in #6.

**Comment by StoccoDavide** [comment]
Hi! Thank you for reporting the bug!

Davide
