### ISSUE TITLE
Error in point inside plane

### ISSUE THREAD

**Issue by ppizarror** [StoccoDavide/acme#9]
Hi! I found an error while checking points inside the plane. That happened because the distance is being measured from the normal of the plane, thus points "behind" are always inside, because the distance is negative, and always less than ``tolerance``, see the following case:

```cpp
plane pxy(point(0, 0, 0), vec3(0, 0, 1));
ASSERT_TRUE(pxy.isInside(point(0, 0, 0))); // PASS
ASSERT_FALSE(pxy.isInside(point(0, 0, -10))); // ERROR!
```

With #8, now the condition is fixed:

```cpp
plane pxy(point(0, 0, 0), vec3(0, 0, 1));
ASSERT_TRUE(pxy.isInside(point(0, 0, 0))); // PASS
ASSERT_FALSE(pxy.isInside(point(0, 0, -10))); // PASS
```

Another case, but more complex:

```cpp
point pA(5.18, -4.14, 5);
point pB(-1, -6, 0);
point pC(-2.38, -0.97, 0);
triangle t(pA, pB, pC);
plane p(pA, t.normal());
ASSERT_TRUE(IsCoplanar(p, t)); // PASS

// Check points within coplanar
point pD(-3.50312, -3.66466, -1.39187);
point pE(2.83708, -3.95799, 3.28633);
point pF(2.83708, -13.95799, 3.28633);
double TOL = 1e-4;

// Test is inside distance plane
ASSERT_TRUE(p.isInside(pD, TOL)); // PASS
ASSERT_TRUE(p.isInside(pE, TOL)); // PASS
ASSERT_FALSE(p.isInside(pF, TOL)); // PASS!
```

If the signed distance is used, ``p.signedDistance(pF)`` returns ``-1.62068``, which is less than ``TOL``, but this point is OUTSIDE the plane. See https://mathinsight.org/distance_point_plane

**Comment by StoccoDavide** [comment]
Hi! I've merged your pull request. I'll address the `signedDistance()` issue tomorrow.
I'm also starting thinking about removing `Utils` dependency, so be ready!

I'm still no sure if renaming `acme.hh` to `acme.h` will be a problem for my codes.

Many thanks for reporting the issue,
Davide

**Comment by ppizarror** [comment]
Nice, thanks!
